nms:
  magmalte:
    image:
      repository: shiveshwavelabs/magmalte
      tag: master-feb
      pullPolicy: IfNotPresent

    env:
      api_host: orc8r-nginx-proxy
      mysql_host: postgresql
      mysql_user: postgres
      mysql_pass: postgres

  nginx:
    image:
      pullPolicy: IfNotPresent

    service:
      type: LoadBalancer

  secret:
    certs: orc8r-secrets-certs

nginx:

  replicas: 1

  image:
    repository: shiveshwavelabs/nginx
    tag: master-feb

  spec:
    hostname:

  service:
    type: LoadBalancer

controller:

  replicas: 1

  image:
    repository: shiveshwavelabs/controller
    tag: master-feb

metrics:
  prometheus:
    includeOrc8rAlerts: true
    create: true

  prometheusCache:
    create: true
    limit: 500000

  prometheusConfigurer:
    create: true

  alertmanager:
    create: true

  alertmanagerConfigurer:
    create: true

  metrics:
    volumes:
      prometheusConfig:
        volumeSpec:
          persistentVolumeClaim:
            claimName: promcfg
      prometheusData:
        volumeSpec:
          persistentVolumeClaim:
            claimName: promdata

  userGrafana:
    image:
      tag: 6.7.6

    volumes:
      datasources:
        volumeSpec:
          persistentVolumeClaim:
            claimName: grafanadatasources

      dashboardproviders:
        volumeSpec:
          persistentVolumeClaim:
            claimName: grafanaproviders

      dashboards:
        volumeSpec:
          persistentVolumeClaim:
            claimName: grafanadashboards

      grafanaData:
        volumeSpec:
          persistentVolumeClaim:
            claimName: grafanadata
